test: env

diff --git a/atlantis.yaml b/atlantis.yaml
--- a/atlantis.yaml
+++ b/atlantis.yaml
@@ -8,12 +8,14 @@ workflows:
       steps:
       - env:
           name: TF_VAR_cloudflare_api_token
-          command: 'echo "$CLOUDFLARE_API_TOKEN"'
+          command: |
+            if [ -z "$TF_VAR_cloudflare_api_token" ]; then
+              echo "Error: TF_VAR_cloudflare_api_token is not set"
+              exit 1
+            fi
+            echo "TF_VAR_cloudflare_api_token is set to $TF_VAR_cloudflare_api_token"
       - init
       - plan
     apply:
       steps:
-      - env:
-          name: TF_VAR_cloudflare_api_token
-          command: 'echo "$CLOUDFLARE_API_TOKEN"'
       - apply
